remote_theme: "mmistakes/minimal-mistakes@4.23.0"
plugins: ["jekyll-include-cache", "jekyll-feed"]
include: ["_pages"]

logo: https://www.gravatar.com/avatar/cf9d2998c0d9cb26334028f72185fe38
minimal_mistakes_skin: "contrast"
title: "Luciferian Locutions"
subtitle: "One lightbringer among many"
author:
  name: "Alexis"
  avatar: https://www.gravatar.com/avatar/cf9d2998c0d9cb26334028f72185fe38
  bio: "I am a mutualist, existentialist atheist, transgender philosopher with chronic tension headaches, OCD, autism, and (probably) bipolar. I am currently getting a Bachelor's in Computer Science with a minor in philosophy at Penn State University."
  location: "California"
search: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
