remote_theme: "mmistakes/minimal-mistakes@4.23.0"
plugins: ["jekyll-include-cache", "jekyll-feed"]

logo: https://yt3.ggpht.com/yti/ANoDKi7j-ErL9pPCHK38AoudrFprzPxx_3yA3Ld0UdTu=s108-c-k-c0x00ffffff-no-rj
minimal_mistakes_skin: "neon"
title: "The Brain-Damaged Philosopher"
subtitle: "Unscripted speech, premeditated thought."
description: "My landing page and impromptu blog, which I probably won't write on much."
author: "BDP"
search: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

comments:
  provider: "disqus"
  disqus:
    shortname: "the-brain-damaged-philosopher"
