remote_theme: "mmistakes/minimal-mistakes@4.23.0"
plugins: ["jekyll-include-cache", "jekyll-feed"]
include: ["_pages"]

logo: https://yt3.ggpht.com/yti/ANoDKi7j-ErL9pPCHK38AoudrFprzPxx_3yA3Ld0UdTu=s108-c-k-c0x00ffffff-no-rj
minimal_mistakes_skin: "contrast"
title: "The Brain-Damaged Philosopher"
subtitle: "Unscripted speech, premeditated thought."
author:
  name: "The Brain-Damaged Philosopher"
  avatar: https://yt3.ggpht.com/yti/ANoDKi7j-ErL9pPCHK38AoudrFprzPxx_3yA3Ld0UdTu=s108-c-k-c0x00ffffff-no-rj
  bio: "I am an amateur philosopher with post-concussion syndrome. I am currently getting a Bachelor's in Computer Science with a minor in philosophy at Penn State University."
  location: "California"
search: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

comments:
  provider: "disqus"
  disqus:
    shortname: "the-brain-damaged-philosopher"
