remote_theme: "mmistakes/minimal-mistakes@4.23.0"

plugins:
  - jekyll-include-cache
  - jekyll-feed

include: ["_pages"]

logo: ./assets/logo.png
minimal_mistakes_skin: "contrast"
title: "Alexis' Journal"
author:
  name: "Alexis Purslane"
  avatar: ./assets/avatar.jpg
  bio: "I am a queer, egoist, mutualist anarchist, existentialist atheist, and transgender philosopher. I have chronic tension headaches, OCD, autism, and GAD. I am currently getting a Bachelor's in Computer Science at Penn State University."
  links:
    - label: "Business Website"
      url: "https://alexisdumas.org"
    - label: "Pronouns and LGBT Info"
      url: "https://en.pronouns.page/@Alexis__1"
    - lable: "Mastodon"
      url: "https://mastodon.lol/@alexispurslane"
    - label: "GitHub"
      url: "https://github.com/alex-dumas"
    - label: "Reddit"
      url: "https://www.reddit.com/user/mammon-of-lilith"
search: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
