theme: jekyll-theme-minimal
logo: https://media.istockphoto.com/vectors/human-brain-icon-in-line-style-vector-id1208432311?k=6&m=1208432311&s=612x612&w=0&h=f6RgZujVlOb3XW1n907D5oLJ2aEHmAtfwB4guDqrASo=
