remote_theme: "mmistakes/minimal-mistakes@4.23.0"

plugins:
  - jekyll-include-cache
  - jekyll-feed

include: ["_pages"]

logo: ./assets/logo.png
minimal_mistakes_skin: "contrast"
title: "Alexis' Journal"
subtitle: "...with time I shall be less and less a worker of misfortune..."
author:
  name: "Alexis Purslane"
  avatar: ./assets/avatar.jpg
  bio: "Hi! I'm a poly trans lesbian interested in writing and philosophy. My philosphical outlook is existentialist athiest and queer, egoist, mutualist anarchist, with interests in Daoism and perspectivism. I have OCD, GAD, autism, possibly ADHD, and chronic tension migraines. I am currently enrolled in the computer science baccalaureate program at Penn State University."
  links:
    - label: "Business Website"
      url: "https://alexisdumas.org"
    - label: "Pronouns and LGBT Info"
      url: "https://en.pronouns.page/@Alexis__1"
    - label: "Mastodon"
      url: "https://mastodon.lol/@alexispurslane"
    - label: "GitHub"
      url: "https://github.com/alex-dumas"
    - label: "Reddit"
      url: "https://www.reddit.com/user/mammon-of-lilith"

search: true

paginate: 5
paginate_path: /page:num/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
