remote_theme: "mmistakes/minimal-mistakes@4.23.0"

plugins:
  - jekyll-include-cache
  - jekyll-feed

include: ["_pages"]

logo: ./assets/logo.png
minimal_mistakes_skin: "contrast"
title: "Luciferian Locutions"
subtitle: "'Tis better to reign in Hell..."
author:
  name: "Alexis Purslane Dumas"
  avatar: ./assets/avatar.jpg
  bio: "I am an **individualist anarchist**, **existentialist atheist**, **transgender** philosopher. I have chronic tension headaches, OCD, autism, and am (probably) bipolar. I am currently getting a Bachelor's in Computer Science with a minor in philosophy at Penn State University."
  links:
    - label: "Business Website"
      url: "https://alexisdumas.org"
    - label: "Pronouns and LGBT Info"
      url: "https://en.pronouns.page/@Alexis__1"
    - label: "GitHub"
      url: "https://github.com/alex-dumas"
    - label: "Reddit"
      url: "https://www.reddit.com/user/mammon-of-lilith"
search: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
